blueprint:
  name: deCONZ - Vimar ZigBee Green 3905
  description: >
    Philips Hue Tap 
  domain: automation
  source_url: https://github.com/rafuz/ha-blueprints/blob/main/deconz_philips_hue_tap.yaml
  input:
    remote:
      name: Remote
      description: Philips Hue Tap
      selector:
        device:
          integration: deconz
          manufacturer: Philips
          model: ZGPSWITCH
    button_one_single_press:
      name: 1 button - Single press
      description: Action to run on a single press of the button 1
      default: []
      selector:
        action: {}
    button_two_single_press:
      name: 2 button - Single press
      description: Action to run on a single press of the button 2
      default: []
      selector:
        action: {}
    button_three_single_press:
      name: 3 button - Single press
      description: Action to run on a single press of the button 3
      default: []
      selector:
        action: {}
    button_four_single_press:
      name: 4 button - Single press
      description: Action to run on a single press of the button 4
      default: []
      selector:
        action: {}

        
mode: restart
max_exceeded: silent

trigger:
- platform: event
  event_type: deconz_event
  event_data:
    device_id: !input 'remote'

action:
- variables:
    event: '{{ trigger.event.data.event }}'
- choose:
  - conditions:
    - '{{ event == 34 }}'
    sequence: !input 'button_one_single_press'
  - conditions:
    - '{{ event == 16 }}'
    sequence: !input 'button_two_single_press'
  - conditions:
    - '{{ event == 17 }}'
    sequence: !input 'button_three_single_press'
  - conditions:
    - '{{ event == 18 }}'
    sequence: !input 'button_four_single_press'
