blueprint:
  name: z2mqtt - Vimar ZigBee Green 3905
  description: >
    Vimar Zigbee Green (4 buttons), based on Vimar ZGP 3905 
  domain: automation
  source_url: https://github.com/rafuz/ha-blueprints/blob/main/z2mqtt_vimar_tap_3905.yaml
  input:
    remote:
      name: Vimar 3905 ZGP
      description: zigbee2mqtt action entity to use
      selector:
        entity:
          domain:
            - sensor
          multiple: false
    button_one_single_press:
      name: 1 button - Single press
      description: Action to run on a single press of the button 1
      default: []
      selector:
        action: {}
    button_two_single_press:
      name: 2 button - Single press
      description: Action to run on a single press of the button 2
      default: []
      selector:
        action: {}
    button_three_single_press:
      name: 3 button - Single press
      description: Action to run on a single press of the button 3
      default: []
      selector:
        action: {}
    button_four_single_press:
      name: 4 button - Single press
      description: Action to run on a single press of the button 4
      default: []
      selector:
        action: {}
    button_1_and_3_single_press:
      name: 1 and 3 buttons - Single press
      description: Action to run on a single press of buttons 1 and 3
      default: []
      selector:
        action: {}
    button_2_and_4_single_press:
      name: 2 and 4 buttons - Single press
      description: Action to run on a single press of buttons 2 and 4
      default: []
      selector:
        action: {}

        
mode: restart
max_exceeded: silent

trigger:
- platform: state
  entity_id: !input remote

action:
- variables:
    command: "{{ trigger.to_state.state }}"
- choose:
  - conditions:
    - "{{ command == 'press_1' }}"
    sequence: !input 'button_one_single_press'
  - conditions:
    - "{{ command == 'press_2' }}"
    sequence: !input 'button_two_single_press'
  - conditions:
    - "{{ command == 'press_3' }}"
    sequence: !input 'button_three_single_press'
  - conditions:
    - "{{ command == 'press_4' }}"
    sequence: !input 'button_four_single_press'
  - conditions:
    - "{{ command == 'press_1_and_3' }}"
    sequence: !input 'button_1_and_3_single_press'
  - conditions:
    - "{{ command == 'press_2_and_4' }}"
    sequence: !input 'button_2_and_4_single_press'
