blueprint:
  name: Zigbee2MQTT - Vimar ZigBee Green 3905
  description: >
    Vimar Zigbee Green (4 buttons), based on Vimar ZGP 3905 
  domain: automation
  source_url: https://github.com/rafuz/ha-blueprints/blob/main/z2mqtt_vimar_tap_3905.yaml
  input:
    remote:
      name: Remote
      description: Vimar 3905
      selector:
        device:
          integration: mqtt
          manufacturer: EnOcean
          model: "Pushbutton transmitter module (PTM 215ZE)"
    button_one_single_press:
      name: 1 button - Single press
      description: Action to run on a single press of the button 1
      default: []
      selector:
        action: {}
    button_two_single_press:
      name: 2 button - Single press
      description: Action to run on a single press of the button 2
      default: []
      selector:
        action: {}
    button_three_single_press:
      name: 3 button - Single press
      description: Action to run on a single press of the button 3
      default: []
      selector:
        action: {}
    button_four_single_press:
      name: 4 button - Single press
      description: Action to run on a single press of the button 4
      default: []
      selector:
        action: {}

        
mode: restart
max_exceeded: silent

trigger:
- platform: device
  domain: mqtt
  event_type: action
  device_id: !input 'remote'

action:
- variables:
    event: '{{ trigger.payload }}'
- choose:
  - conditions:
    - '{{ event == 34 }}'
    sequence: !input 'button_one_single_press'
  - conditions:
    - '{{ event == 24 }}'
    sequence: !input 'button_two_single_press'
  - conditions:
    - '{{ event == 20 }}'
    sequence: !input 'button_three_single_press'
  - conditions:
    - '{{ event == 18 }}'
    sequence: !input 'button_four_single_press'
